### PR TITLE
Fix Python 3 support

### PR DESCRIPTION
**Pull request by abloemert**

### CODE REVIEW

**Comment by jackjansen** [comment]
Looks good. I don't have time to test in the coming weeks, so I'll just trust you.

**Comment by abloemert** [comment]
Hi @jackjansen, can you create a release for this change? (e.g. `v0.2.4`)

**Comment by jackjansen** [comment]
@abloemert Yes, I should have done so, but there's too many things taking up my time. Sorry to ask this, but if I haven't addressed this in a few weeks can you please ping me?

**Comment by abloemert** [comment]
@jackjansen would be great if it can be released somewhere within the next 2 weeks. Let me know if there is anything I can help with.

**Comment by RajeshwariSubramaniam** [comment]
@jackjansen Could you please create a release for this change?

**Comment by ThejashwiniSwamy** [comment]
Hey @jackjansen, we are waiting to use the new version of this tool.
Please create new release - v0.2.4

**Comment by abloemert** [comment]
See also PR #6

**Pull request merged**
