### PR TITLE
Prepare next release

### PR DESCRIPTION
**Pull request by abloemert**

### CODE REVIEW

**Comment by abloemert** [comment]
@jackjansen can you merge this Pull Request, create a tag and upload it to PyPi?

**Comment by abloemert** [comment]
@jackjansen can you release the next version to prevent the need of yet another fork of `py-dom-xpath`?

**Comment by abloemert** [comment]
@jackjansen another ping

**Comment by jackjansen** [comment]
@abloemert sorry for taking such a long time, but 0.2.4 is up on PyPi.

**Comment by abloemert** [comment]
Great, thanks!

**Pull request merged**
